#!/bin/bash
#echo $1
count=0
while read link
do
id=${link##*=}
id="=$id "
id=$(cat /home/rachit/hacks/dl_files/tahuko_files/links_db | grep $id | wc -l)
if [ $id == 0 ]; then
curl  $link > /tmp/out
#flashurl=$(cat /tmp/out | grep "flashvars" | tail -n +2 | cut -d "=" -f3 | cut -d "'" -f1 | sed 's/ /%20/g')
#name=$(echo $flashurl | rev | cut -d"/" -f1 | rev | sed 's/%20/_/g')
#curl -# $flashurl > /tmp/out1
#swfextract -m /tmp/out1 -o $name.mp3

#check for old version, i.e .swf file
cat /tmp/out | grep "flashvars" | tail -n +2 > /tmp/out1
version=$(wc -l /tmp/out1 | cut -d" " -f1)
#if version=0, ==> new version, not swf
##else old version


if [ "$version" == "0" ]; then
	cat /tmp/out | grep "soundFile" > /tmp/out2
	while read line           
	do
		line=${line##*:\"} 
		line=${line%\"*}
		url=$(python /home/rachit/hacks/dl_files/tahuko_files/soundFile_decoder.py $line)
		name=${url##*/}
                name=$(echo $name | sed 's/ /_/g')
		url=$(echo $url | sed 's/ /%20/g')
		id=${link##*/}
		id=${id##*=}
		echo $id " : "$url

	done </tmp/out2

else
	while read line
	do
		line_check=$line
		line_check=$(echo $line | cut -d"\"" -f2 | cut -d"/" -f3)
		if [ "$line_check" == "www.youtube.com" ]; then
			url=$(echo $line | cut -d"\"" -f2 | cut -d";" -f1 | cut -d"&" -f1)
			#echo "youtubeurl "$url
		else
			line=${line##*=}
			line=${line%\'*}
			line=${line%\"*}
			line=$(echo $line | sed 's/ /%20/g')
			ext=${line##*.}
                	name=$(echo ${line##*/} | sed 's/%20/_/g')
	                name=${name%.*}
			url=$line
		fi

		id=${link##*/}
		id=${id##*=}
		echo $id " : "$url

	done </tmp/out1
	
fi
let count=count+1
let mod=count%10
if [ $mod -eq 0 ]; then
string="$count done!"
notify-send $string
fi
fi
done <$1
